DROP TABLE IF EXISTS cities CASCADE;
CREATE TABLE cities(
    id SERIAL PRIMARY KEY NOT NULL,
    city VARCHAR(255) NOT NULL,
    lat VARCHAR(255) NOT NULL,
    long VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL
);