insert into events (event, brewery, date, location, ticket_link, ticket_price, description) 
values
('Layer Cake', 'Aquamarine', '04/12/2022', '83 Prairieview Way', 'https://yandex.ru', 20, 'engineer 24/365 experiences'),
('Eye of Vichy, The (Oeil de Vichy, L'')', 'Maroon', '07/09/2022', '8 Waxwing Center', 'https://usnews.com', 14, 'productize strategic relationships'),
('Toy Story Toons: Partysaurus Rex', 'Green', '09/05/2022', '26 Delaware Way', 'https://google.it', 11, 'cultivate scalable action-items'),
('Descent, The', 'Pink', '19/07/2022', '06699 Valley Edge Pass', 'http://comsenz.com', 22, 'strategize innovative web-readiness'),
('Incir Reçeli', 'Yellow', '04/05/2022', '10 Comanche Crossing', 'http://usda.gov', 18, 'deploy B2C web-readiness'),
('Dug''s Special Mission', 'Pink', '12/12/2022', '21051 Spohn Park', 'https://telegraph.co.uk', 27, 'matrix distributed e-commerce'),
('Claire''s Knee (Genou de Claire, Le)', 'Turquoise', '22/07/2022', '5933 Tomscot Street', 'http://dell.com', 17, 'reinvent integrated convergence'),
('Champagne', 'Purple', '11/09/2022', '68619 Corben Terrace', 'http://harvard.edu', 13, 'evolve 24/365 convergence'),
('Five People You Meet in Heaven, The', 'Teal', '19/07/2022', '27 Fairview Junction', 'https://last.fm', 26, 'incentivize out-of-the-box supply-chains'),
('Ro.Go.Pa.G.', 'Fuscia', '23/10/2022', '51 Crowley Road', 'https://narod.ru', 20, 'extend next-generation e-services'),
('Far Off Place, A', 'Puce', '02/10/2022', '17319 Mcbride Terrace', 'http://vkontakte.ru', 10, 'incubate wireless infomediaries'),
('Teen Witch', 'Yellow', '15/12/2021', '8748 Hollow Ridge Road', 'https://independent.co.uk', 27, 'integrate bricks-and-clicks channels'),
('My Mother''s Castle (Château de ma mère, Le)', 'Aquamarine', '09/11/2022', '03857 Killdeer Parkway', 'https://yolasite.com', 20, 'incentivize bleeding-edge infrastructures'),
('Curse of the Blair Witch', 'Violet', '08/09/2022', '6645 Elgar Point', 'https://aboutads.info', 23, 'visualize proactive synergies'),
('Paradise Alley', 'Blue', '21/06/2022', '3 Buhler Place', 'https://phpbb.com', 13, 'exploit interactive niches'),
('George Washington', 'Aquamarine', '26/08/2022', '2 Morning Park', 'https://sfgate.com', 28, 'syndicate B2C deliverables'),
('Greening of Whitney Brown, The', 'Red', '27/06/2022', '39221 Farmco Street', 'https://indiegogo.com', 18, 'incentivize one-to-one metrics'),
('Three Comrades', 'Indigo', '02/12/2021', '248 Surrey Junction', 'https://merriam-webster.com', 20, 'embrace seamless web services'),
('Crew, The', 'Yellow', '08/12/2021', '16 Esker Park', 'https://ameblo.jp', 14, 'unleash impactful initiatives'),
('I Love You, I Love You (Je t''aime je t''aime)', 'Fuscia', '05/09/2022', '52 Brentwood Point', 'https://g.co', 29, 'synergize world-class deliverables'),
('Egyptian, The', 'Pink', '17/01/2022', '213 Hollow Ridge Place', 'http://imgur.com', 18, 'engineer open-source methodologies'),
('String, The (Le fil)', 'Goldenrod', '30/11/2022', '6 Redwing Terrace', 'https://cocolog-nifty.com', 17, 'unleash collaborative platforms'),
('Secret Life of Girls, The', 'Orange', '01/11/2022', '966 Londonderry Lane', 'http://wikia.com', 21, 'expedite back-end metrics'),
('The Gamers: Hands of Fate', 'Green', '12/05/2022', '1 Lindbergh Terrace', 'https://walmart.com', 28, 'optimize vertical schemas'),
('Thunderbolt (Pik lik feng)', 'Indigo', '29/12/2021', '0 Memorial Junction', 'https://icq.com', 29, 'exploit world-class experiences'),
('Nightmare on Elm Street 4: The Dream Master, A', 'Crimson', '30/12/2021', '90 Myrtle Alley', 'http://china.com.cn', 13, 'implement cross-media functionalities'),
('Criminal Life of Archibaldo de la Cruz, The (Ensayo de un crimen)', 'Turquoise', '26/11/2022', '081 Algoma Place', 'http://discuz.net', 29, 'enable compelling relationships'),
('Godzilla Raids Again (Gojira no gyakushû)', 'Purple', '11/02/2022', '260 Lakeland Point', 'https://amazonaws.com', 28, 'harness open-source mindshare'),
('Book of Fate, The (Kohtalon kirja)', 'Blue', '05/12/2021', '24617 7th Point', 'http://jigsy.com', 25, 'strategize strategic e-business'),
('Crimson Rivers 2: Angels of the Apocalypse (Rivières pourpres II - Les anges de l''apocalypse, Les)', 'Purple', '23/12/2021', '20 Old Gate Drive', 'http://abc.net.au', 22, 'strategize impactful vortals'),
('Nirvana', 'Indigo', '22/12/2022', '1 Upham Court', 'http://tiny.cc', 29, 'strategize dot-com infomediaries'),
('Familiar Ground', 'Fuscia', '27/09/2022', '4198 Tomscot Court', 'http://friendfeed.com', 29, 'synergize enterprise models'),
('Guardian Angel', 'Purple', '12/12/2021', '5940 3rd Point', 'https://craigslist.org', 21, 'transition mission-critical technologies'),
('The Wayward Girl', 'Purple', '14/04/2022', '08763 Donald Trail', 'https://chronoengine.com', 10, 'extend transparent niches'),
('Gas, Inspector Palmu! (Kaasua, komisario Palmu!)', 'Pink', '27/11/2021', '66 Magdeline Lane', 'https://photobucket.com', 16, 'engage innovative niches'),
('Flight 93', 'Fuscia', '19/02/2022', '7054 Birchwood Terrace', 'http://globo.com', 13, 'incubate rich bandwidth'),
('Watchers', 'Purple', '01/12/2021', '1 Golden Leaf Avenue', 'https://spotify.com', 12, 'implement interactive functionalities'),
('Dinotopia', 'Khaki', '11/07/2022', '47978 4th Drive', 'https://studiopress.com', 24, 'recontextualize dot-com mindshare'),
('Jay and Silent Bob Go Down Under', 'Fuscia', '02/12/2021', '7656 Cambridge Alley', 'http://unesco.org', 23, 'transform dot-com e-tailers'),
('Lord of War', 'Fuscia', '27/03/2022', '1743 7th Court', 'https://freewebs.com', 12, 'integrate efficient bandwidth'),
('Wittgenstein', 'Orange', '09/10/2022', '53660 Rusk Place', 'http://dagondesign.com', 11, 'reinvent bricks-and-clicks web services'),
('Crime Zone', 'Fuscia', '07/06/2022', '166 New Castle Terrace', 'https://ameblo.jp', 23, 'whiteboard revolutionary channels'),
('Girl, The', 'Aquamarine', '12/03/2022', '6575 Wayridge Trail', 'https://cafepress.com', 12, 'whiteboard value-added initiatives'),
('Nil By Mouth', 'Goldenrod', '21/10/2022', '50 Kings Place', 'http://qq.com', 28, 'engineer interactive mindshare'),
('Manual of Love 2 (Manuale d''amore (capitoli successivi))', 'Pink', '10/12/2022', '29152 Iowa Lane', 'http://sfgate.com', 17, 'architect bleeding-edge interfaces'),
('G.I. Joe: The Revenge of Cobra', 'Orange', '01/03/2022', '94 Sommers Way', 'http://lulu.com', 19, 'synthesize granular architectures'),
('Four Rooms', 'Pink', '27/08/2022', '550 Dawn Drive', 'https://wordpress.org', 24, 'cultivate integrated channels'),
('Shaolin Kung Fu Mystagogue (Da mo mi zong)', 'Khaki', '25/12/2022', '8 Sachs Pass', 'https://narod.ru', 18, 'target killer portals'),
('Joseph and the Amazing Technicolor Dreamcoat', 'Fuscia', '27/01/2022', '37 Nobel Park', 'http://paginegialle.it', 26, 'expedite extensible architectures'),
('Beach, The', 'Yellow', '15/03/2022', '724 Vernon Center', 'http://fema.gov', 19, 'syndicate holistic models'),
('Salt of the Earth', 'Crimson', '16/05/2022', '4 Sloan Pass', 'http://state.gov', 12, 'streamline mission-critical platforms'),
('Mr. Belvedere Goes to College', 'Purple', '13/07/2022', '682 Merrick Court', 'https://123-reg.co.uk', 21, 'cultivate customized e-markets'),
('Kill! (Kiru)', 'Pink', '12/09/2022', '6 Saint Paul Place', 'http://google.com.hk', 21, 'embrace viral convergence'),
('I Melt with You', 'Goldenrod', '06/07/2022', '98019 Victoria Lane', 'https://printfriendly.com', 20, 'monetize cross-platform action-items'),
('Yolki 2', 'Yellow', '07/02/2022', '6004 Bultman Hill', 'https://people.com.cn', 23, 'unleash strategic vortals'),
('Pulgasari', 'Indigo', '05/12/2022', '170 Goodland Place', 'http://quantcast.com', 10, 'scale innovative partnerships'),
('Killers', 'Maroon', '07/05/2022', '871 Novick Drive', 'http://e-recht24.de', 26, 'incentivize user-centric e-markets'),
('Gunfighters', 'Crimson', '09/08/2022', '7702 Oakridge Center', 'http://networksolutions.com', 13, 'productize turn-key communities'),
('Thirteen Ghosts (a.k.a. Thir13en Ghosts)', 'Turquoise', '24/06/2022', '76605 Jackson Parkway', 'http://usgs.gov', 12, 'orchestrate visionary metrics'),
('Green Zone', 'Khaki', '26/03/2022', '570 Saint Paul Crossing', 'http://usa.gov', 10, 'visualize dot-com technologies'),
('Besieged (a.k.a. L'' Assedio)', 'Maroon', '01/06/2022', '15 Pankratz Alley', 'https://ow.ly', 13, 'utilize revolutionary e-tailers'),
('Ordeal, The (Calvaire)', 'Turquoise', '19/03/2022', '1 Kensington Pass', 'https://symantec.com', 13, 'generate distributed relationships'),
('Kisses', 'Crimson', '07/10/2022', '96 Daystar Parkway', 'http://unesco.org', 19, 'mesh proactive deliverables'),
('Hawaii', 'Purple', '12/12/2021', '64585 Southridge Street', 'http://surveymonkey.com', 23, 'synergize clicks-and-mortar e-commerce'),
('Evening with Kevin Smith 2: Evening Harder, An', 'Aquamarine', '31/03/2022', '38 Namekagon Parkway', 'https://bbb.org', 18, 'revolutionize sticky convergence'),
('Salmonberries', 'Yellow', '10/07/2022', '1784 Tony Park', 'http://nydailynews.com', 21, 'generate user-centric paradigms'),
('Bridge Too Far, A', 'Green', '17/03/2022', '7216 Shoshone Plaza', 'http://cnet.com', 14, 'incentivize sticky methodologies'),
('Greater Promise, A (Iskateli Schastya)', 'Red', '13/02/2022', '75 Kenwood Court', 'https://mit.edu', 25, 'mesh out-of-the-box markets'),
('Buried Alive', 'Khaki', '11/10/2022', '83209 Northport Hill', 'http://ted.com', 14, 'target enterprise e-services'),
('Rites of May, The (Itim) ', 'Maroon', '12/06/2022', '3 Knutson Point', 'http://issuu.com', 18, 'envisioneer leading-edge infomediaries'),
('Outbreak', 'Aquamarine', '18/07/2022', '964 Autumn Leaf Road', 'http://ebay.co.uk', 15, 'grow scalable action-items'),
('Madame Sin', 'Turquoise', '05/12/2021', '2 Elka Point', 'http://sourceforge.net', 13, 'mesh interactive synergies'),
('A Home at the End of the World', 'Pink', '28/11/2022', '2296 John Wall Alley', 'https://free.fr', 16, 'revolutionize rich bandwidth'),
('A True Mob Story', 'Khaki', '09/08/2022', '798 Bonner Way', 'http://alibaba.com', 26, 'streamline granular architectures'),
('On Guard (Bossu, Le)', 'Crimson', '18/06/2022', '24 Iowa Plaza', 'http://indiegogo.com', 23, 'deliver dynamic web-readiness'),
('All About My Mother (Todo sobre mi madre)', 'Pink', '15/07/2022', '0945 Pawling Drive', 'http://earthlink.net', 25, 'transition revolutionary e-markets'),
('High Road to China', 'Crimson', '05/06/2022', '521 Saint Paul Terrace', 'https://upenn.edu', 30, 'deploy leading-edge action-items'),
('Man of Straw (Untertan, Der)', 'Pink', '20/07/2022', '27758 Kings Plaza', 'http://technorati.com', 18, 'transition clicks-and-mortar markets'),
('Offender', 'Yellow', '22/09/2022', '9 Weeping Birch Junction', 'https://scribd.com', 22, 'utilize synergistic synergies'),
('Private Life of Don Juan, The', 'Puce', '09/02/2022', '39210 Myrtle Way', 'https://instagram.com', 27, 'enable wireless partnerships'),
('Endangered Species', 'Crimson', '05/07/2022', '61507 Hallows Crossing', 'http://51.la', 22, 'disintermediate innovative web services'),
('Until the Light Takes Us', 'Crimson', '07/05/2022', '4 Crescent Oaks Place', 'http://uol.com.br', 17, 'iterate user-centric experiences'),
('Blindman', 'Khaki', '04/08/2022', '83439 Karstens Terrace', 'http://github.io', 19, 'orchestrate visionary action-items'),
('Super Size Me', 'Yellow', '25/11/2021', '719 Lindbergh Road', 'https://fda.gov', 15, 'synergize web-enabled mindshare'),
('Jimi Hendrix', 'Puce', '04/10/2022', '6 Division Point', 'https://youtu.be', 15, 'incentivize seamless supply-chains'),
('Gypsy', 'Mauv', '14/02/2022', '347 Jenna Terrace', 'http://usatoday.com', 16, 'reintermediate bricks-and-clicks infomediaries'),
('Jeffrey', 'Indigo', '22/12/2022', '6783 Express Junction', 'https://cam.ac.uk', 29, 'synthesize clicks-and-mortar mindshare'),
('Enforcer, The', 'Teal', '28/06/2022', '48 Truax Court', 'https://networksolutions.com', 12, 'enable enterprise networks'),
('My Week with Marilyn', 'Teal', '16/05/2022', '94 Larry Avenue', 'http://technorati.com', 30, 'transition front-end bandwidth'),
('Report to the Commissioner', 'Blue', '21/07/2022', '37839 Talmadge Center', 'http://latimes.com', 23, 'aggregate customized networks'),
('Any Number Can Play', 'Khaki', '21/09/2022', '5 Crest Line Alley', 'https://vimeo.com', 17, 'enhance bricks-and-clicks portals'),
('Scarlet Dove, The (Tulipunainen kyyhkynen)', 'Orange', '02/02/2022', '5658 Erie Road', 'http://ehow.com', 10, 'iterate compelling deliverables'),
('Pleasure Garden, The', 'Crimson', '12/04/2022', '460 Northport Parkway', 'https://samsung.com', 20, 'scale user-centric content'),
('Stargate: The Ark of Truth', 'Purple', '27/12/2021', '18 Forster Junction', 'http://bizjournals.com', 29, 'scale 24/7 e-commerce'),
('Jesus Camp', 'Mauv', '01/07/2022', '95 Grasskamp Trail', 'https://yelp.com', 16, 'iterate synergistic vortals'),
('Sällskapsresan II - Snowroller', 'Fuscia', '02/05/2022', '67560 Grasskamp Park', 'http://opensource.org', 21, 'drive clicks-and-mortar mindshare'),
('The Youngest Profession', 'Puce', '31/03/2022', '89106 Burning Wood Trail', 'https://fastcompany.com', 14, 'innovate impactful e-tailers'),
('Edge of Madness', 'Mauv', '01/02/2022', '5 Hanson Road', 'http://infoseek.co.jp', 22, 'transition revolutionary partnerships'),
('Other One, The', 'Maroon', '11/01/2022', '12407 Boyd Hill', 'http://clickbank.net', 11, 'synergize synergistic e-business'),
('Boys, Les', 'Turquoise', '21/05/2022', '4 Eliot Pass', 'https://e-recht24.de', 26, 'drive turn-key deliverables')
